server:
    port: 8082
spring:
    kafka:
        consumer:
            bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS:-10.5.0.3:9092}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            group-id: "group_id"
topic:
    name: t.message.order
app:
    data-file: ${DATA_FILE:-/temp/}
