server:
  port: 8080

topic:
  name: t.food.order

app:
  data-file: ${DATA_FILE:-/temp/}

spring:
  kafka:
    producer:
      bootstrap-servers: 10.5.0.3:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: "group_id"
